import {
    BiLogoAndroid,
    BiLogoApple,
    BiLogoCss3,
    BiLogoFirebase,
    BiLogoGit,
    BiLogoGithub,
    BiLogoJavascript,
    BiLogoReact,
    BiLogoRedux,
    BiLogoTypescript,
    BiLogoVisualStudio,
    BiLogoWindows,
} from "react-icons/bi";
import { CgNpm } from "react-icons/cg";
import { DiLinux } from "react-icons/di";
import {
    HiOutlineArrowPath,
    HiOutlineBeaker,
    HiOutlineBugAnt,
    HiOutlineCloud,
    HiOutlineCodeBracket,
    HiOutlineCircleStack,
    HiOutlineCreditCard,
    HiOutlineDevicePhoneMobile,
    HiOutlineFingerPrint,
    HiOutlineGlobeAlt,
    HiOutlineLanguage,
    HiOutlineLockClosed,
    HiOutlineMagnifyingGlass,
    HiOutlineRocketLaunch,
    HiOutlineServer,
    HiOutlineSparkles,
    HiOutlineWrenchScrewdriver,
} from "react-icons/hi2";
import {
    SiAndroidstudio,
    SiAnthropic,
    SiCocoapods,
    SiDocker,
    SiExpo,
    SiGithubcopilot,
    SiGooglemaps,
    SiGooglegemini,
    SiGradle,
    SiGraphql,
    SiHtml5,
    SiJest,
    SiMicrosoftazure,
    SiNextdotjs,
    SiOpenai,
    SiPaypal,
    SiRazorpay,
    SiReactquery,
    SiRedux,
    SiReduxsaga,
    SiSemrush,
    SiSentry,
    SiStripe,
    SiTailwindcss,
    SiVite,
    SiXcode,
    SiYarn,
} from "react-icons/si";
import { SKILLS } from "./index";

/** @type {import('../types').SkillMeta} */
export const DEFAULT_SKILL_META = {
    icon: HiOutlineCodeBracket,
    color: "text-purple-400",
};

/** @type {Record<string, import('../types').SkillMeta>} */
export const SKILL_META = {
    JavaScript: { icon: BiLogoJavascript, color: "text-yellow-400" },
    TypeScript: { icon: BiLogoTypescript, color: "text-blue-400" },
    HTML5: { icon: SiHtml5, color: "text-orange-500" },
    CSS3: { icon: BiLogoCss3, color: "text-blue-400" },
    "React.js": { icon: BiLogoReact, color: "text-cyan-400" },
    "Next.js": { icon: SiNextdotjs, color: "text-neutral-200" },
    "Tailwind CSS": { icon: SiTailwindcss, color: "text-cyan-400" },
    Vite: { icon: SiVite, color: "text-violet-400" },
    "Responsive Web Design": { icon: HiOutlineDevicePhoneMobile, color: "text-pink-400" },
    "SEO Optimization": { icon: HiOutlineMagnifyingGlass, color: "text-blue-400" },
    "React Native": { icon: BiLogoReact, color: "text-cyan-400" },
    "Android Development": { icon: BiLogoAndroid, color: "text-green-500" },
    "iOS Development": { icon: BiLogoApple, color: "text-neutral-300" },
    Expo: { icon: SiExpo, color: "text-neutral-200" },
    "App Store & Play Store Deployment": { icon: HiOutlineGlobeAlt, color: "text-emerald-400" },
    Redux: { icon: BiLogoRedux, color: "text-purple-500" },
    "Redux Toolkit": { icon: SiRedux, color: "text-purple-500" },
    "Redux Thunk": { icon: BiLogoRedux, color: "text-purple-400" },
    "Redux Saga": { icon: SiReduxsaga, color: "text-green-400" },
    Zustand: { icon: HiOutlineCircleStack, color: "text-amber-400" },
    "TanStack Query": { icon: SiReactquery, color: "text-red-400" },
    "REST APIs": { icon: HiOutlineServer, color: "text-slate-400" },
    GraphQL: { icon: SiGraphql, color: "text-pink-500" },
    Axios: { icon: HiOutlineCodeBracket, color: "text-indigo-400" },
    Firebase: { icon: BiLogoFirebase, color: "text-orange-400" },
    WebSockets: { icon: HiOutlineServer, color: "text-violet-400" },
    "N-Genius Payment Gateway": { icon: HiOutlineCreditCard, color: "text-blue-400" },
    PayPal: { icon: SiPaypal, color: "text-blue-500" },
    Razorpay: { icon: SiRazorpay, color: "text-blue-600" },
    "Stripe Payment Gateway": { icon: SiStripe, color: "text-indigo-400" },
    "Face ID / Biometric Login": { icon: HiOutlineFingerPrint, color: "text-cyan-400" },
    "Authentication Workflows": { icon: HiOutlineLockClosed, color: "text-amber-400" },
    Arabic: { icon: HiOutlineLanguage, color: "text-emerald-400" },
    English: { icon: HiOutlineLanguage, color: "text-sky-400" },
    "Microsoft Azure": { icon: SiMicrosoftazure, color: "text-blue-500" },
    Docker: { icon: SiDocker, color: "text-blue-400" },
    CDN: { icon: HiOutlineCloud, color: "text-sky-400" },
    "CI/CD": { icon: HiOutlineArrowPath, color: "text-orange-400" },
    FileZilla: { icon: HiOutlineServer, color: "text-red-500" },
    "Google Maps Integration": { icon: SiGooglemaps, color: "text-green-500" },
    SEMrush: { icon: SiSemrush, color: "text-orange-500" },
    "Performance Optimization": { icon: HiOutlineRocketLaunch, color: "text-yellow-400" },
    Jest: { icon: SiJest, color: "text-red-500" },
    Sentry: { icon: SiSentry, color: "text-purple-400" },
    "React Native Testing Library": { icon: HiOutlineBeaker, color: "text-pink-400" },
    Debugging: { icon: HiOutlineBugAnt, color: "text-lime-400" },
    Flipper: { icon: HiOutlineWrenchScrewdriver, color: "text-blue-400" },
    "Claude AI": { icon: SiAnthropic, color: "text-orange-400" },
    ChatGPT: { icon: SiOpenai, color: "text-emerald-400" },
    "Google Gemini": { icon: SiGooglegemini, color: "text-blue-400" },
    "GitHub Copilot": { icon: SiGithubcopilot, color: "text-neutral-200" },
    "Cursor Agent": { icon: HiOutlineSparkles, color: "text-purple-400" },
    Git: { icon: BiLogoGit, color: "text-orange-500" },
    GitHub: { icon: BiLogoGithub, color: "text-neutral-300" },
    "VS Code": { icon: BiLogoVisualStudio, color: "text-blue-500" },
    "Android Studio": { icon: SiAndroidstudio, color: "text-green-500" },
    Xcode: { icon: SiXcode, color: "text-blue-500" },
    Gradle: { icon: SiGradle, color: "text-green-600" },
    CocoaPods: { icon: SiCocoapods, color: "text-red-500" },
    Yarn: { icon: SiYarn, color: "text-blue-500" },
    NPM: { icon: CgNpm, color: "text-red-500" },
    macOS: { icon: BiLogoApple, color: "text-neutral-300" },
    Windows: { icon: BiLogoWindows, color: "text-blue-400" },
    Linux: { icon: DiLinux, color: "text-neutral-300" },
};

/** @type {Record<import('../types').SkillCategoryKey, string>} */
export const SKILL_CATEGORY_TITLES = {
    languages: "Languages",
    frontend: "Frontend",
    mobile: "Mobile",
    stateManagement: "State Management",
    apiIntegration: "API Integration",
    paymentGateways: "Payment Gateways",
    security: "Security",
    localization: "Localization",
    cloudAndDeployment: "Cloud & Deployment",
    ecommerceAndTools: "E-commerce & Tools",
    testingAndDebugging: "Testing & Debugging",
    aiTools: "AI Tools",
    tools: "Tools",
    packageManagers: "Package Managers",
    operatingSystems: "Platforms",
};

/** @returns {import('../types').SkillCategory[]} */
export const getSkillCategories = () =>
    Object.entries(SKILLS).map(([key, skills]) => ({
        title: SKILL_CATEGORY_TITLES[key] ?? key,
        skills: skills.map((name) => ({
            name,
            ...(SKILL_META[name] ?? DEFAULT_SKILL_META),
        })),
    }));
